openapi: 3.0.0
info:
  title: Auth
  version: 1.0.0
  description: Customer endpoint documentation
schemes:
  - http
  - https

paths:
  /ping:
    get:
      summary: Get server health status
      tags:
        - Healthcheck
      responses:
        200:
          description: Server is running smoothly
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
  /customers:
    post:
      summary: Create a new customer
      description: Endpoint to create a new customer.
      tags:
        - Customer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/customers'
      responses:
        '201':
          $ref: '#/components/responses/created'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '500':
          $ref: '#/components/exceptions/serverError'

    get:
      summary: Get all customers
      description: Endpoint to get all the customers
      tags:
        - Customer
      responses:
        '200':
          $ref: '#/definition/responses/ok'

  /customers/{id}:
    get:
      summary: Get customer by id
      description: Endpoint to get a single customer by id
      tags:
        - Customer
      parameters:
        - name: id
          in: path
          description: Customer's id
          required: true
          schema:
            $ref: '#/components/schemas/customerId'
          example: 'c85aedc9c339491cb2c0560359c9b7ec'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '409':
          $ref: '#/components/exceptions/conflict'
        '500':
          $ref: '#/components/exceptions/serverError'

    patch:
      summary: Update customer by id
      description: Endpoint to update a customer's details by id
      tags:
        - Customer
      parameters:
        - name: id
          in: path
          description: Customer's id
          required: true
          schema:
            $ref: '#/definitions/customerId'
          example: 'c85aedc9c339491cb2c0560359c9b7ec'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/updatecustomer'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '409':
          $ref: '#/components/exceptions/conflict'
        '500':
          $ref: '#/components/exceptions/serverError'

    delete:
      summary: Delete customer by id
      description: Endpoint to delete a customer's details by id
      tags:
        - Customer
      parameters:
        - name: id
          in: path
          description: Customer's id
          required: true
          schema:
            $ref: '#/definitions/customerId'
          example: 'c85aedc9c339491cb2c0560359c9b7ec'
      responses:
        '204':
          $ref: '#/definitions/responses/noContent'
        '500':
          $ref: '#/definitions/exceptions/serverError'

  /auth/signup:
    post:
      summary: Signup a new customer
      description: Endpoint to create a new customer.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/customers'
      responses:
        '201':
          $ref: '#/components/responses/created'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '500':
          $ref: '#/components/exceptions/serverError'

  /auth/login:
    post:
      summary: Login a customer
      description: Endpoint to login a customer.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/login'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '500':
          $ref: '#/components/exceptions/serverError'

  /auth/logout:
    post:
      summary: logout current customer
      description: Endpoint to logout a customer and delete the auth token.
      tags:
        - Authentication
      security:
        - bearerAuth: []
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '500':
          $ref: '#/components/exceptions/serverError'

  /auth/otp:
    post:
      summary: Send  OTP
      description: Endpoint to send verification OTP to the customer email.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/sendotp'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '500':
          $ref: '#/components/exceptions/serverError'

  /auth/verify:
    post:
      summary: Verify  OTP
      description: Endpoint to verify OTP sent to the customer email.
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/verifyotp'
      responses:
        '200':
          $ref: '#/components/responses/ok'
        '400':
          $ref: '#/components/exceptions/badRequest'
        '500':
          $ref: '#/components/exceptions/serverError'

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: >-
        Enter the token with the `Bearer: ` prefix, e.g. "Bearer abcde12345".

  responses:
    created:
      description: Customer successfully created
    ok:
      description: Ok!
    noContent:
      description: Customer successfully deleted

  exceptions:
    badRequest:
      description: 'Bad Request:: Invalid request payload'
    notFound:
      description: 'Not found:: Customer not found'
    serverError:
      description: 'Server Error:: Internal Server Error'
    conflict:
      description: 'Conflict:: Customer already exists.'

definitions:
  customers:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
      email:
        type: string
        format: email
      password:
        type: string
      passwordConfirm:
        type: string
    required:
      - firstName
      - lastName
      - email
      - password
      - passwordConfirm

  customerId:
    type: string
    format: uuid

  updatecustomer:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
    required:
      - firstName
      - lastName

  login:
    type: object
    properties:
      email:
        type: string
      password:
        type: string
    required:
      - email
      - password

  sendotp:
    type: object
    properties:
      email:
        type: string
    required:
      - email

  verifyotp:
    type: object
    properties:
      email:
        type: string
      otp:
        type: string
    required:
      - email
      - otp
